# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: enum_sample_development

